import logging
from datetime import datetime
from pathlib import Path

import pandas as pd
import streamlit as st

from demo import _ensure_utc
from extract_frames import extract_frames
from features_price import load_price_features
from features_vlm import build_vlm_features
from openrouter_vlm import score_frame
from train_eval import train_directional_model

st.set_page_config(page_title="VLM Demo Control Room", layout="wide")
logger = logging.getLogger(__name__)


def _parse_horizons(raw: str) -> list[int]:
    parts = [p.strip() for p in raw.replace(";", ",").split(",")]
    return [int(p) for p in parts if p]


def _render_frame_browser(scored_rows: list[dict]):
    st.subheader("Frame Browser")
    if not scored_rows:
        st.info("Run the analysis to inspect scored frames.")
        return

    df = pd.DataFrame(scored_rows)
    frame_options = df.index.tolist()
    selected_idx = st.slider(
        "Choose frame index",
        min_value=min(frame_options),
        max_value=max(frame_options),
        value=frame_options[0],
    )
    selected = df.loc[selected_idx]
    st.image(
        selected["frame"],
        caption=f"Frame {selected_idx} | t={selected['ts']:.2f}s | "
        f"valence={selected['valence']:.2f} | "
        f"arousal={selected['arousal']:.2f} | "
        f"intensity={selected['intensity']:.2f} | "
        f"confidence={selected['confidence']:.2f}",
        use_column_width=True,
    )
    st.dataframe(df, use_container_width=True)


def main():
    st.title("VLM Demo Control Room")
    st.caption(
        "Inspect frame sampling, VLM affect scores, aggregated features, and price "
        "labels generated by the demo pipeline."
    )

    with st.sidebar:
        st.header("Inputs")
        video_path = st.text_input(
            "Video path",
            value="data/videos/dal_ceo_clip.mp4",
            help="Path to the interview video.",
        )
        frames_dir = st.text_input(
            "Frames directory",
            value="data/frames/dal_clip",
            help="Frames will be cached here.",
        )
        bars_path = st.text_input(
            "Price bars CSV",
            value="data/prices/DAL_1min.csv",
            help="Minute-level OHLCV CSV generated by src.fetch_prices.",
        )
        ticker = st.text_input("Ticker", value="DAL")
        event_time_str = st.text_input(
            "Event time (ISO 8601)",
            value="2024-05-10T14:30:00Z",
            help="Prefer UTC (append 'Z').",
        )
        t_start = st.number_input("Start time (s)", value=0.0)
        t_end = st.number_input("End time (s)", value=210.0, min_value=0.0)
        frame_stride = st.number_input("Frame stride (s)", value=30.0, min_value=0.1)
        window = st.number_input("Aggregation window (s)", value=60, min_value=1)
        min_conf = st.slider("Minimum confidence", min_value=0.0, max_value=1.0, value=0.5)
        horizons_raw = st.text_input("Prediction horizons (minutes)", value="5,60")
        run_button = st.button("Run analysis", type="primary")

    scored_rows: list[dict] = []
    feature_df = pd.DataFrame()
    px_features = {}
    labels = {}
    horizon_results = []

    if run_button:
        try:
            event_ts = _ensure_utc(datetime.fromisoformat(event_time_str))
        except ValueError as exc:
            st.error(f"Invalid event time: {exc}")
            return

        horizons = _parse_horizons(horizons_raw)
        if not horizons:
            st.error("Provide at least one prediction horizon.")
            return

        Path(frames_dir).mkdir(parents=True, exist_ok=True)

        status = st.empty()
        status.info("Extracting frames…")
        try:
            frames = extract_frames(
                video_path,
                frames_dir,
                t_start,
                t_end,
                frame_stride,
            )
        except Exception as exc:  # noqa: BLE001
            st.exception(exc)
            return

        if not frames:
            st.warning("No frames extracted. Check the video path and time range.")
            return
        status.success(f"Extracted {len(frames)} frames.")

        progress = st.progress(0)
        status.info("Scoring frames with VLM…")
        scored = []
        total = len(frames)
        for idx, row in enumerate(frames, start=1):
            try:
                payload = score_frame(row["frame"])
            except Exception as exc:  # noqa: BLE001
                progress.empty()
                st.exception(exc)
                return
            scored.append({**row, **payload})
            progress.progress(idx / total)
            status.info(f"Scoring frames with VLM… ({idx}/{total})")
        progress.empty()
        st.success("VLM scoring complete.")
        scored_rows = scored

        try:
            feature_df = build_vlm_features(
                scored_rows,
                window_s=window,
                min_conf=min_conf,
            )
        except Exception as exc:  # noqa: BLE001
            st.exception(exc)
            return

        st.info(
            f"Built VLM feature matrix with shape {feature_df.shape[0]} x {feature_df.shape[1]}."
        )

        try:
            px_features, labels = load_price_features(
                bars_path,
                event_ts,
                horizons,
            )
        except Exception as exc:  # noqa: BLE001
            st.exception(exc)
            return

        st.success(
            f"Loaded price features for {ticker} aligned to {event_ts.isoformat()}."
        )

        combined = feature_df.assign(**px_features)
        results = []
        for horizon in horizons:
            label_key = f"dir_{horizon}m"
            if label_key not in labels:
                results.append(
                    {
                        "horizon_m": horizon,
                        "direction": "n/a",
                        "prob_up": None,
                        "holdout_acc": None,
                        "note": "Missing price label.",
                    }
                )
                continue

            label_series = pd.Series([labels[label_key]] * len(combined))
            model, score_val = train_directional_model(combined, label_series)

            if model is None:
                direction = "↑" if labels[label_key] else "↓"
                results.append(
                    {
                        "horizon_m": horizon,
                        "direction": direction,
                        "prob_up": None,
                        "holdout_acc": None,
                        "note": "Insufficient samples for model training.",
                    }
                )
                continue

            probs = model.predict_proba(combined.values)[-1, 1]
            direction = "↑" if probs >= 0.5 else "↓"
            results.append(
                {
                    "horizon_m": horizon,
                    "direction": direction,
                    "prob_up": round(probs, 3),
                    "holdout_acc": round(score_val, 3) if score_val is not None else None,
                    "note": "",
                }
            )

        horizon_results = results

    _render_frame_browser(scored_rows)

    if not feature_df.empty:
        st.subheader("Aggregated VLM Features")
        st.dataframe(feature_df, use_container_width=True)
        chart_df = feature_df[["v_mean", "a_mean", "i_mean"]].copy()
        chart_df.index.name = "window"
        st.line_chart(chart_df)

    if px_features:
        st.subheader("Price Features @ Event")
        st.json(px_features)

    if labels:
        st.subheader("Future Return Labels")
        st.json(labels)

    if horizon_results:
        st.subheader("Directional Predictions")
        st.dataframe(pd.DataFrame(horizon_results), use_container_width=True)


if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
    )
    main()
